### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [frankrolf/git-for-type-designers#1]
Is this on github to gather contributions? :) 

If so, please add a license to the repo so that the contributions are legit; I recommend the same as wikipedia.

To do this, I suggest to add either a line near the top/bottom that says 

`Copyright © 2015 Frank Grießhammer (@frankrolf) This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).`

and a copy of http://creativecommons.org/licenses/by-sa/4.0/legalcode.txt as a LICENSE.txt

**Comment by frankrolf** [comment]
This is an extended transcript of a short talk I gave at Typographics TypeLab.
The full text will be parsed for inclusion to the [TypeLab](http://typographics.com/typelab/) site; so I prefer to not put the copyright string in there. 
I have added a `LICENSE.md` file, which includes the string and a link the the full license text.

**Comment by davelab6** [comment]
:+1: Thanks!
